### PR TITLE
Fix mypy linting

### PR DESCRIPTION
**Pull request by tesmond**
**Change**
- adjusted type hints to pass mypy
- remove unnecessary type hint ignores
- black re-format

### CODE REVIEW

**Comment by farahats9** [comment]
@tesmond Sorry I didn't have the time to look at this, should I take a look or did you close it because it has something wrong?

**Comment by ArVar** [comment]
@farahats9 , it looks promising and could fix the problems, preventing the merge of your PR into sqlmodel. I would recommend to take a look at it.

**Comment by tesmond** [comment]
@farahats9 sorry, I created the fork and made the changes, however, you can only open 1 fork per original repo. I thought instead I could take a direct fork of sqlmodel and get that working and make sure the tests passed etc. However, I did not get round to it.

You are welcome to use the changes, I do not think there was anything wrong, just I do not know if it would be enough for all the tests to pass in the original repo.

**Comment by ArVar** [comment]
@tesmond I had look into it. There are two clusters of problems. One is a mypy issue/bug with overloaded methods and their signatures . The other cluster is related to the way TypeVar handles definitions without bounds. This you can solve easily like here: https://github.com/farahats9/sqlmodel/commit/9266acb2bfe2c17f152c16adb9dcd0a0afdc2fac
There is also another issue regarding Forward References for recent sqlalchemy. This I couldn't further investigate.

**Pull request closed without merging**
